// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqLPYIeEg9QRQ5-nHP8bQZfPUVFQ_SVGQ',
    appId: '1:563129663089:web:b4cbe26dbe52b04e5b25d0',
    messagingSenderId: '563129663089',
    projectId: 'whatsapp-f6fc8',
    authDomain: 'whatsapp-f6fc8.firebaseapp.com',
    storageBucket: 'whatsapp-f6fc8.appspot.com',
    measurementId: 'G-H6V7XE86M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj_PRSkZHEmcoG9d1_OFM4-SHpl4ChbF0',
    appId: '1:563129663089:android:82d6d28ef0a9387b5b25d0',
    messagingSenderId: '563129663089',
    projectId: 'whatsapp-f6fc8',
    storageBucket: 'whatsapp-f6fc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCWlgaIkkqaXGjOITqIDQ7Co6y5OlFqec',
    appId: '1:563129663089:ios:aaacd41bb204b7d65b25d0',
    messagingSenderId: '563129663089',
    projectId: 'whatsapp-f6fc8',
    storageBucket: 'whatsapp-f6fc8.appspot.com',
    iosClientId: '563129663089-3trlh57igquuv5k4um5hg53tsqv75lg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsApp',
  );
}
